In [1]:
import os
import pandas as pd
import openpyxl
path = "process/DATA_fixed.xlsx"

df = pd.read_excel(path)

In [2]:
df

,Style,Color,FP/DC,Product ID,Page Status,Current Production Type,Units Sold (since 2016),Style + Color
0,"""17"" JERSEY CREW LIGHTWEIGHT",Amalfi/Pure Snow,FP,7613124214832,DRAFT,NaN,NaN,"""17"" JERSEY CREW LIGHTWEIGHT+Amalfi/Pure Snow"
1,"""21"" JERSEY CREW LIGHTWEIGHT",Night Navy/Pure Snow,FP,7534966538288,DRAFT,NaN,NaN,"""21"" JERSEY CREW LIGHTWEIGHT+Night Navy/Pure Snow"
2,"""25"" JERSEY CREW LIGHTWEIGHT",Black/Pure Snow,FP,7718869237808,DRAFT,NaN,NaN,"""25"" JERSEY CREW LIGHTWEIGHT+Black/Pure Snow"
3,"""3"" JERSEY CREW LIGHTWEIGHT",Night Navy/Pure Snow,FP,7534968897584,DRAFT,NaN,NaN,"""3"" JERSEY CREW LIGHTWEIGHT+Night Navy/Pure Snow"
4,"""4"" JERSEY CREW LIGHTWEIGHT",Waxed Loden/Pure Snow,FP,7532914114608,DRAFT,NaN,NaN,"""4"" JERSEY CREW LIGHTWEIGHT+Waxed Loden/Pure Snow"
...,...,...,...,...,...,...,...,...
13144,ZEBRA T LIGHTWEIGHT,Alabaster/Black,FP,4664508284976,DRAFT,NaN,NaN,ZEBRA T LIGHTWEIGHT+Alabaster/Black
13145,ZEBRA T LIGHTWEIGHT,Gunmetal/Black,FP,4664508350512,DRAFT,NaN,NaN,ZEBRA T LIGHTWEIGHT+Gunmetal/Black
13146,ZEBRA V LIGHTWEIGHT,Gunmetal/Black,FP,4674543681584,DRAFT,NaN,NaN,ZEBRA V LIGHTWEIGHT+Gunmetal/Black
13147,ZOE V-NECK COTTON,Nickle/Pure Snow,FP,3822027735088,DRAFT,NaN,NaN,ZOE V-NECK COTTON+Nickle/Pure Snow
13148,ZOE V-NECK COTTON,Pinot Noir/Darkest Indigo,FP,3821821755440,DRAFT,NaN,NaN,ZOE V-NECK COTTON+Pinot Noir/Darkest Indigo

In [3]:
path_sat = "SUMMARIZE ALL TIME.xlsx"
df_sat = pd.read_excel(path_sat, sheet_name="ALL TIME SALES")

In [4]:
df_sat

,Product ID,Month,Order name,Product title at time of sale,Product variant SKU at time of sale,Shipping region,Orders,Gross sales,Discounts,Returns,Net sales,Shipping charges,Duties,Additional fees,Taxes,Total sales,Net items sold
0,10640442580,2017-05-01,#1860,COLD SHOULDER TOP COTTON,K38C3W618-PURE SNOW-S/M,Oregon,1,99.0,0.0,0.0,99.0,0,0,0,0.00,99.00,1
1,10536512148,2017-05-01,#1878,LOBSTER V - NECK COTTON,K38CA3BSW217-MICA BEIGE/RUBY GRAPEFRUIT-S/M,Massachusetts,1,109.0,-10.9,0.0,98.1,0,0,0,0.00,98.10,1
2,10208889354,2017-05-01,#1765,Gift Card,NaN,California,0,0.0,0.0,0.0,0.0,0,0,0,0.00,0.00,1
3,10640442836,2017-05-01,#1854,COLD SHOULDER RUFFLE TOP COTTON MERCER,K38A7W619-ORCHID-X/S,Colorado,1,109.0,0.0,0.0,109.0,0,0,0,0.00,109.00,1
4,10640442580,2017-05-01,#1860,COLD SHOULDER TOP COTTON,K38C3W618-PURE RED-S/M,Oregon,1,99.0,0.0,0.0,99.0,0,0,0,0.00,99.00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340479,7865240584240,2026-05-01,#278884,RIHANNA CHUNKY CARDI COTTON,K56C1W709-ALMOND BUTTER-X/L,Wisconsin,1,154.0,0.0,0.0,154.0,0,0,0,8.47,162.47,1
340480,7924021854256,2026-05-01,#278962,SAILING ZIP HOODIE COTTON,K56C2W727-BREAKER WHITE/KHAKI STRIPE-S/M,North Carolina,1,152.0,0.0,0.0,152.0,0,0,0,11.02,163.02,1
340481,7878592757808,2026-05-01,#279167,AMERICAN DREAM CREW COTTON,K56C3W027-WHITE/RED/INDIGO-M/L,Florida,1,154.0,0.0,0.0,154.0,0,0,0,11.55,165.55,1
340482,7924021854256,2026-05-01,#278085,SAILING ZIP HOODIE COTTON,K56C2W727-BREAKER WHITE/KHAKI STRIPE-S/M,New York,1,152.0,-15.2,0.0,136.8,0,0,0,11.97,148.77,1
340483,7657949036592,2026-05-01,#279068,POCKET FULL OF SUNSHINE CREW COTTON,K56CPE2W034-BREAKER WHITE/TUSCAN SUN-X/S,Wisconsin,1,148.0,0.0,0.0,148.0,0,0,0,8.14,156.14,1

In [5]:
df_sat_net_sales = df_sat.groupby("Product ID")["Net sales"].sum().reset_index()

In [6]:
df_sat_net_items= df_sat.groupby("Product ID")["Net items sold"].sum().reset_index()

In [7]:
df_sat_check = df_sat_net_sales.merge(df_sat_net_items, on="Product ID")

In [8]:
df_sat_check = df_sat_check.sort_values("Net items sold", ascending=True)

In [9]:
df_sat_check

          Product ID   Net sales  Net items sold
7623   7260330459184        0.00               0
6238   7025148035120        0.00               0
11626  7782715064368        0.00               0
11621  7780465475632        0.00               0
3611   4665220825136        0.00               0
...              ...         ...             ...
2798   4520817066032   289284.53            2418
1921   4375356702768   316095.70            2658
2817   4520858320944   388379.19            3323
11932  7865240584240   548406.28            3694
2747   4495419572272  1021156.68            8718

[12261 rows x 3 columns]

In [10]:
df_p = df 
df_p = df_p.merge(df_sat_check, on="Product ID", how="left")

In [11]:
df_p = df_p.dropna(subset=["Product ID"])

In [21]:
# df_p = df_p.sort_values(by=['Style + Color', 'Product ID'], ascending=[True, False])
df_p

,Style,Color,FP/DC,Product ID,Page Status,Current Production Type,Units Sold (since 2016),Style + Color,Net sales,Net items sold
33,"*SALE* - ""15"" JERSEY CREW LIGHTWEIGHT",Red Ginger/Pure Snow,DC,7719047036976,DRAFT,"*SALE* - ""15"" JERSEY CREW LIGHTWEIGHT+Red Ging...",NaN,"*SALE* - ""15"" JERSEY CREW LIGHTWEIGHT+Red Ging...",124.00,1
34,"*SALE* - ""15"" JERSEY CREW LIGHTWEIGHT",Red Ginger/Pure Snow,DC,7777741111344,DRAFT,"*SALE* - ""15"" JERSEY CREW LIGHTWEIGHT+Red Ging...",NaN,"*SALE* - ""15"" JERSEY CREW LIGHTWEIGHT+Red Ging...",NaN,0
44,"*SALE* - ""27"" JERSEY CREW COTTON",Red Chile/Breaker White,DC,7775296978992,DRAFT,"*SALE* - ""27"" JERSEY CREW COTTON+Red Chile/Bre...",NaN,"*SALE* - ""27"" JERSEY CREW COTTON+Red Chile/Bre...",124.00,1
43,"*SALE* - ""27"" JERSEY CREW COTTON",Red Chile/Breaker White,DC,7587930996784,DRAFT,"*SALE* - ""27"" JERSEY CREW COTTON+Red Chile/Bre...",NaN,"*SALE* - ""27"" JERSEY CREW COTTON+Red Chile/Bre...",NaN,0
66,"*SALE* - ""79"" JERSEY CREW LIGHTWEIGHT",Racing Sails/Pure Snow,DC,7757537706032,DRAFT,"*SALE* - ""79"" JERSEY CREW LIGHTWEIGHT+Racing S...",NaN,"*SALE* - ""79"" JERSEY CREW LIGHTWEIGHT+Racing S...",99.00,1
...,...,...,...,...,...,...,...,...,...,...
13119,XOXO CREW LIGHTWEIGHT,Half Moon/Cherry Pastille,FP,7162475577392,DRAFT,XOXO CREW LIGHTWEIGHT+Half Moon/Cherry Pastill...,NaN,XOXO CREW LIGHTWEIGHT+Half Moon/Cherry Pastille,3148.88,25
13121,XOXO CREW LIGHTWEIGHT,Half Moon/Cherry Pastille,FP,7194910064688,DRAFT,XOXO CREW LIGHTWEIGHT+Half Moon/Cherry Pastill...,NaN,XOXO CREW LIGHTWEIGHT+Half Moon/Cherry Pastille,629.43,5
13120,XOXO CREW LIGHTWEIGHT,Half Moon/Cherry Pastille,FP,7177167765552,DRAFT,XOXO CREW LIGHTWEIGHT+Half Moon/Cherry Pastill...,NaN,XOXO CREW LIGHTWEIGHT+Half Moon/Cherry Pastille,NaN,0
13142,ZEBRA SKULL LIGHTWEIGHT,Gunmetal/Black,FP,4637393158192,DRAFT,ZEBRA SKULL LIGHTWEIGHT+Gunmetal/Black+FP,NaN,ZEBRA SKULL LIGHTWEIGHT+Gunmetal/Black,1348.00,12
13143,ZEBRA SKULL LIGHTWEIGHT,Gunmetal/Black,FP,4682215981104,DRAFT,ZEBRA SKULL LIGHTWEIGHT+Gunmetal/Black+FP,NaN,ZEBRA SKULL LIGHTWEIGHT+Gunmetal/Black,130.00,1

In [13]:
df_p["Current Production Type"] = df_p["Style + Color"].str.strip() + "+" + df_p["FP/DC"].astype(str)

In [14]:
df_p = df_p.sort_values(by=['Current Production Type','Product ID'], ascending=[True, False])

In [15]:
df_p = df_p[df_p['Current Production Type'].duplicated(keep=False)]

In [16]:
df_p['Net items sold'] = df_p['Net items sold'].fillna(0)

In [17]:
df_p = df_p.sort_values(by=['Current Production Type','Net items sold'], ascending=[True, False])

In [18]:
df_p['Net items sold'] = df_p['Net items sold'].astype(int)

In [19]:
# df_final = df_p.loc[df_p['Units Sold (since 2016)'] < 6]

In [20]:
df_final = df_p.sort_values(by=['Current Production Type','Net items sold'], ascending=[True, False])

In [22]:
df_final

,Style,Color,FP/DC,Product ID,Page Status,Current Production Type,Units Sold (since 2016),Style + Color,Net sales,Net items sold
33,"*SALE* - ""15"" JERSEY CREW LIGHTWEIGHT",Red Ginger/Pure Snow,DC,7719047036976,DRAFT,"*SALE* - ""15"" JERSEY CREW LIGHTWEIGHT+Red Ging...",NaN,"*SALE* - ""15"" JERSEY CREW LIGHTWEIGHT+Red Ging...",124.00,1
34,"*SALE* - ""15"" JERSEY CREW LIGHTWEIGHT",Red Ginger/Pure Snow,DC,7777741111344,DRAFT,"*SALE* - ""15"" JERSEY CREW LIGHTWEIGHT+Red Ging...",NaN,"*SALE* - ""15"" JERSEY CREW LIGHTWEIGHT+Red Ging...",NaN,0
44,"*SALE* - ""27"" JERSEY CREW COTTON",Red Chile/Breaker White,DC,7775296978992,DRAFT,"*SALE* - ""27"" JERSEY CREW COTTON+Red Chile/Bre...",NaN,"*SALE* - ""27"" JERSEY CREW COTTON+Red Chile/Bre...",124.00,1
43,"*SALE* - ""27"" JERSEY CREW COTTON",Red Chile/Breaker White,DC,7587930996784,DRAFT,"*SALE* - ""27"" JERSEY CREW COTTON+Red Chile/Bre...",NaN,"*SALE* - ""27"" JERSEY CREW COTTON+Red Chile/Bre...",NaN,0
66,"*SALE* - ""79"" JERSEY CREW LIGHTWEIGHT",Racing Sails/Pure Snow,DC,7757537706032,DRAFT,"*SALE* - ""79"" JERSEY CREW LIGHTWEIGHT+Racing S...",NaN,"*SALE* - ""79"" JERSEY CREW LIGHTWEIGHT+Racing S...",99.00,1
...,...,...,...,...,...,...,...,...,...,...
13119,XOXO CREW LIGHTWEIGHT,Half Moon/Cherry Pastille,FP,7162475577392,DRAFT,XOXO CREW LIGHTWEIGHT+Half Moon/Cherry Pastill...,NaN,XOXO CREW LIGHTWEIGHT+Half Moon/Cherry Pastille,3148.88,25
13121,XOXO CREW LIGHTWEIGHT,Half Moon/Cherry Pastille,FP,7194910064688,DRAFT,XOXO CREW LIGHTWEIGHT+Half Moon/Cherry Pastill...,NaN,XOXO CREW LIGHTWEIGHT+Half Moon/Cherry Pastille,629.43,5
13120,XOXO CREW LIGHTWEIGHT,Half Moon/Cherry Pastille,FP,7177167765552,DRAFT,XOXO CREW LIGHTWEIGHT+Half Moon/Cherry Pastill...,NaN,XOXO CREW LIGHTWEIGHT+Half Moon/Cherry Pastille,NaN,0
13142,ZEBRA SKULL LIGHTWEIGHT,Gunmetal/Black,FP,4637393158192,DRAFT,ZEBRA SKULL LIGHTWEIGHT+Gunmetal/Black+FP,NaN,ZEBRA SKULL LIGHTWEIGHT+Gunmetal/Black,1348.00,12
13143,ZEBRA SKULL LIGHTWEIGHT,Gunmetal/Black,FP,4682215981104,DRAFT,ZEBRA SKULL LIGHTWEIGHT+Gunmetal/Black+FP,NaN,ZEBRA SKULL LIGHTWEIGHT+Gunmetal/Black,130.00,1

In [23]:
df_final = df_final.loc[df_final['Page Status'] == "DRAFT"]

In [24]:
productID_to_keep = []
style_color_to_keep = []
for i, d in df_final.iterrows():
    if d['Current Production Type'] not in style_color_to_keep:
        style_color_to_keep.append(d['Current Production Type'])
        productID_to_keep.append(d['Product ID'])
    # else:
    #     df_final.drop(i, inplace=True)

In [25]:
df_final_not_keep= df_final[~df_final['Product ID'].isin(productID_to_keep)]

In [26]:
df_final_not_keep = df_final_not_keep.loc[df_final_not_keep['Net items sold'] < 6]

In [27]:
df_final_not_keep

,Style,Color,FP/DC,Product ID,Page Status,Current Production Type,Units Sold (since 2016),Style + Color,Net sales,Net items sold
34,"*SALE* - ""15"" JERSEY CREW LIGHTWEIGHT",Red Ginger/Pure Snow,DC,7777741111344,DRAFT,"*SALE* - ""15"" JERSEY CREW LIGHTWEIGHT+Red Ging...",NaN,"*SALE* - ""15"" JERSEY CREW LIGHTWEIGHT+Red Ging...",NaN,0
43,"*SALE* - ""27"" JERSEY CREW COTTON",Red Chile/Breaker White,DC,7587930996784,DRAFT,"*SALE* - ""27"" JERSEY CREW COTTON+Red Chile/Bre...",NaN,"*SALE* - ""27"" JERSEY CREW COTTON+Red Chile/Bre...",NaN,0
65,"*SALE* - ""79"" JERSEY CREW LIGHTWEIGHT",Racing Sails/Pure Snow,DC,7588158636080,DRAFT,"*SALE* - ""79"" JERSEY CREW LIGHTWEIGHT+Racing S...",NaN,"*SALE* - ""79"" JERSEY CREW LIGHTWEIGHT+Racing S...",NaN,0
74,"*SALE* - ""91"" JERSEY CREW LIGHTWEIGHT",Red Ginger/Pure Snow,DC,7786664460336,DRAFT,"*SALE* - ""91"" JERSEY CREW LIGHTWEIGHT+Red Ging...",NaN,"*SALE* - ""91"" JERSEY CREW LIGHTWEIGHT+Red Ging...",NaN,0
86,"*SALE* - ""R"" MONOGRAM CREW CHUNKY",Pure Snow/Pretty Pink,DC,7632549937200,DRAFT,"*SALE* - ""R"" MONOGRAM CREW CHUNKY+Pure Snow/Pr...",NaN,"*SALE* - ""R"" MONOGRAM CREW CHUNKY+Pure Snow/Pr...",NaN,0
...,...,...,...,...,...,...,...,...,...,...
13110,XOX SLOUCHY PULLOVER,Grey/Red Ginger,FP,4734081630256,DRAFT,XOX SLOUCHY PULLOVER+Grey/Red Ginger+FP,NaN,XOX SLOUCHY PULLOVER+Grey/Red Ginger,NaN,0
13117,XOXO CREW LIGHTWEIGHT,Half Moon,FP,7327199494192,DRAFT,XOXO CREW LIGHTWEIGHT+Half Moon+FP,NaN,XOXO CREW LIGHTWEIGHT+Half Moon,525.00,4
13121,XOXO CREW LIGHTWEIGHT,Half Moon/Cherry Pastille,FP,7194910064688,DRAFT,XOXO CREW LIGHTWEIGHT+Half Moon/Cherry Pastill...,NaN,XOXO CREW LIGHTWEIGHT+Half Moon/Cherry Pastille,629.43,5
13120,XOXO CREW LIGHTWEIGHT,Half Moon/Cherry Pastille,FP,7177167765552,DRAFT,XOXO CREW LIGHTWEIGHT+Half Moon/Cherry Pastill...,NaN,XOXO CREW LIGHTWEIGHT+Half Moon/Cherry Pastille,NaN,0
13143,ZEBRA SKULL LIGHTWEIGHT,Gunmetal/Black,FP,4682215981104,DRAFT,ZEBRA SKULL LIGHTWEIGHT+Gunmetal/Black+FP,NaN,ZEBRA SKULL LIGHTWEIGHT+Gunmetal/Black,130.00,1

In [28]:
productID_to_delete = df_final_not_keep['Product ID'].tolist()

In [29]:
productID_to_delete

import set_sy

print(set_sy.get_token())

/Users/woodenship/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

RuntimeError: Failed to obtain access token (HTTP 400): <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>400 - Oauth error invalid_request</title>
  <meta name="referrer" content="never" />
  <style type="text/css">

    * { border:0; margin:0; padding:0; -moz-box-sizing:border-box; -webkit-box-sizing:border-box; box-sizing:border-box; }
    html,body { height:100%; border:0; margin:0; padding:0; font-family:"Helvetica Neue", Helvetica, Arial, sans-serif; font-weight:300; background:#fff; }
    body { min-height:100%; font-size:16px; line-height:22px; color:#6c6c6c; }
    a { color:#479ccf; }

    h1,h2,h3,h4,h5,h6 { text-align:left; margin:0 0 20px 0; color:#31373D; font-weight:700; }
    h1 { font-size:28px; line-height:48px; margin-bottom:7px; }
    h2 { font-size:20px; font-weight:300; line-height:30px; color:#6c6c6c; }
    h3 { font-size:17px; line-height:30px; position:relative; padding-bottom:18px; margin-bottom:22px; font-weight:400; }
    h3:after { content:""; position:absolute; left:0; bottom:0; height:2px; width:76px; background:#EAEAEA; }
    h4 { font-size:14px; margin-bottom:3px; }

    img { max-width:100%; }

    li { margin-bottom:5px; }

    .next-icon {
      display: inline-block;
      vertical-align: middle;
      background-size: contain;
      background-position: center;
      background-repeat: no-repeat;
      position: relative;
      top: 0.15em;
      fill: currentColor;
      margin-bottom: 5px;
    }

    .next-icon--color-yellow {
      fill: #E9BE33;
    }

    .next-icon--size-40 {
      width: 40px;
      height: 40px;
    }

    .wrapper { min-width:320px; max-width:650px; margin:0 auto; padding:20px; }

    .hero { margin-bottom:30px; }

    .content--block { position:relative; margin-bottom:50px; }
    .content--desc { margin-bottom:32px; position:relative; }
    .content--desc-large { font-size:20px; line-height:28px; }

    .request-id { padding-top:100px; font-size:13px; color:#ccc; }

    @media all and (min-width:500px) {
      body { padding:60px 0; }
      .wrapper { padding:20px 20px 20px 100px; }
      .ico svg { width:40px; height:40px; margin-bottom:0; }
      .hero { margin-bottom:70px; }
      .content--block { margin-bottom:80px; }
      .content--desc .next-icon { position:absolute; left:-70px; top:-7px; }
    }

    @media all and (min-width:900px) {
      .wrapper { padding:20px; }
    }

  </style>
</head>

<body class="status-error status-code-500">

  <div class="wrapper">
    <div class="hero">
      <svg width="160px" height="176px" viewBox="0 0 160 176" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns" role="img" aria-labelledby="hero__logo">
        <title id="hero__logo">Shopify logo</title>
        <defs></defs>
        <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" sketch:type="MSPage">
          <g id="user-action-required-2" sketch:type="MSArtboardGroup" transform="translate(-297.000000, -81.000000)" stroke="#979797" stroke-dasharray="5">
            <g id="shopify-bag-outline" sketch:type="MSLayerGroup" transform="translate(298.000000, 82.000000)">
              <path d="M138.817711,32.9976853 C138.371951,32.7161619 137.887187,32.6604147 137.887187,32.6604147 L123.887534,31.6151547 L113.584904,21.3716063 C113.200436,21.0733588 112.749104,20.9005425 112.286628,20.8085596 L104.647414,174.188624 L158.389365,162.551396 L139.402771,34.070819 C139.402771,34.070819 139.257899,33.2847834 138.817711,32.9976853" id="Fill-1" sketch:type="MSShapeGroup"></path>
              <path d="M104.652986,20.8643068 L99.4292354,22.483763 C97.1196409,15.7244147 93.9714603,10.8994944 90.0264836,8.10655958 C87.070537,6.01325214 83.8137024,5.13244635 80.3144857,5.408395 C79.5984836,4.46347992 78.8323334,3.59939829 77.9742453,2.90534562 C74.1100625,-0.222072416 69.1286936,-0.707073074 63.1694384,1.45591837 C45.436545,7.89750757 37.8224056,30.7622225 35.033619,42.4328993 L19.170132,47.3470151 C19.170132,47.3470151 15.5009693,48.3894878 14.6400951,49.4235984 C13.6956409,50.558054 13.5117649,53.615788 13.5117649,53.615788 L0.300550361,155.58857 L99.4988854,174.183049 L107.138099,20.7778986 C106.043201,20.5632719 104.926014,20.8001975 104.652986,20.8643068 L104.652986,20.8643068 Z M87.081681,12.7586636 C90.1602116,14.9383792 92.375082,19.3061725 93.9491723,24.1812653 L85.6218167,26.7595734 C85.6134587,26.1630783 85.6106727,25.5693706 85.5855987,24.9533641 C85.3850067,19.5932706 84.6550745,15.0777472 83.4153043,11.4207307 C84.7470126,11.5628861 85.9756388,11.9754154 87.081681,12.7586636 L87.081681,12.7586636 Z M62.4868683,33.9286636 C64.7825327,25.0620711 69.1621256,16.0561106 77.4671932,12.5273127 C79.1972995,17.0205372 79.6987796,23.1471547 79.6653476,28.6048058 L62.4868683,33.9286636 L62.4868683,33.9286636 Z M65.2115768,7.08638578 C68.8083035,5.77911389 71.558086,5.87109677 73.6531584,7.23969059 C62.5453743,12.3544964 57.6503714,25.0955194 55.513509,36.0888677 L41.7952423,40.3395918 C44.9099909,29.1929388 51.7774822,11.964266 65.2115768,7.08638578 L65.2115768,7.08638578 Z M74.6366166,82.0524358 C73.8509645,81.6705675 72.9204403,81.2608255 71.8673321,80.8705951 C70.8225819,80.4831521 69.6608197,80.1124332 68.4015474,79.8058236 C67.1506332,79.499214 65.8077809,79.2511389 64.3897067,79.1034088 C62.9883484,78.9612535 61.5173401,78.9138683 59.9906118,79.0030639 C58.5892535,79.0866847 57.3188373,79.3347597 56.2016511,79.7333522 C55.0956089,80.1291573 54.1344387,80.6726926 53.3432145,81.3472337 C52.5547764,82.0217749 51.9307123,82.8245346 51.4905242,83.7499381 C51.0531221,84.669767 50.79681,85.7122396 50.746662,86.8634194 C50.710444,87.7163515 50.8413861,88.5358354 51.1422741,89.3330204 C51.4431622,90.1302054 51.9112103,90.9106662 52.5519904,91.6883397 C53.1927705,92.4688005 54.0062827,93.246474 54.9925269,94.0380843 C55.984343,94.8352693 57.1572493,95.6519658 58.5112455,96.4965359 C60.4057259,97.7090375 62.3419963,99.0804187 64.1863286,100.65249 C66.055735,102.24686 67.8248453,104.044707 69.3460016,106.093417 C70.8838739,108.167213 72.1626481,110.489084 73.0263083,113.095265 C73.8955405,115.718171 74.3357286,118.614238 74.1964285,121.805766 C73.9707625,127.023704 72.8285023,131.522503 70.9368079,135.254778 C69.0701876,138.936881 66.4931371,141.832948 63.3895325,143.929043 C60.3555779,145.98054 56.8396452,147.254363 53.0144665,147.76445 C49.3035138,148.263388 45.319533,148.040399 41.2157542,147.134507 C41.1823222,147.126145 41.1488902,147.117783 41.1182442,147.112208 C41.0848122,147.106633 41.0541662,147.098271 41.0207342,147.089909 C40.9873022,147.084334 40.9538702,147.075972 40.9232242,147.06761 C40.8897921,147.059248 40.8591461,147.053673 40.8257141,147.045311 C38.9005878,146.579822 37.0423254,145.972178 35.2955031,145.266976 C33.5765407,144.570136 31.9606604,143.778525 30.4924382,142.922806 C29.0409319,142.075448 27.7287256,141.169556 26.5920374,140.230216 C25.4664932,139.302025 24.510895,138.340386 23.7614609,137.378747 L28.2914977,122.340939 C29.0548619,122.987606 29.9909581,123.720682 31.0552103,124.467695 C32.1306065,125.225856 33.3397307,126.000743 34.6352209,126.725456 C35.9446412,127.455745 37.3432135,128.13586 38.7835757,128.687758 C40.240654,129.248017 41.7423083,129.677271 43.2300326,129.897472 C44.5422388,130.0898 45.7151451,130.050777 46.7431793,129.819426 C47.7767855,129.585288 48.6599476,129.156034 49.3843078,128.570689 C50.1086679,127.982556 50.674226,127.235543 51.0642661,126.379824 C51.4598782,125.521317 51.6827582,124.554103 51.7273342,123.519992 C51.7719102,122.483094 51.6771862,121.510305 51.4180882,120.562603 C51.1589901,119.614901 50.735518,118.700646 50.1225979,117.780818 C49.5124638,116.866564 48.7212396,115.949522 47.7210655,115.00182 C46.7320353,114.059692 45.542413,113.089691 44.1326968,112.061155 C42.4053764,110.770607 40.7783521,109.368565 39.3240598,107.846666 C37.8836976,106.341492 36.6104953,104.713673 35.5657451,102.9437 C34.5321389,101.193238 33.7186268,99.2978328 33.1920727,97.2435484 C32.6655186,95.1948387 32.4231365,92.9788874 32.5290045,90.5650336 C32.7045226,86.5289361 33.5124627,82.8078104 34.860887,79.4574036 C36.2232413,76.0735484 38.1567256,73.0353259 40.5805461,70.4207821 C43.0545146,67.7532785 46.0578231,65.5038789 49.5236078,63.7729282 C53.0869025,61.9918051 57.1656073,60.7430678 61.6789281,60.1493601 C63.7767865,59.8761988 65.7854929,59.7451929 67.6883313,59.7368308 C69.6162437,59.7284687 71.42993,59.8427505 73.1015303,60.0573772 C74.7926326,60.2720039 76.3332909,60.5869756 77.6984312,60.9716313 C79.0775015,61.3618618 80.2699097,61.8245635 81.2533679,62.3262883 L74.6366166,82.0524358 L74.6366166,82.0524358 Z" id="Fill-10" sketch:type="MSShapeGroup"></path>
          </g>
        </g>
      </g>
    </svg>
    </div>
    <div class="content">
      <div class="content--block">
        <div class="content--desc">
          <svg class="next-icon next-icon--color-yellow next-icon--size-40" role="img" aria-labelledby="content--image-alert">
            <title id="content--image-alert">Alert sign</title>
            <path d="M37.4,37.7H2.6c-0.9,0-1.8-0.5-2.3-1.3c-0.5-0.8-0.5-1.8,0-2.6L17.7,3.7c0.5-0.8,1.3-1.3,2.3-1.3 s1.8,0.5,2.3,1.3l17.4,30.1c0.5,0.8,0.5,1.8,0,2.6C39.2,37.2,38.3,37.7,37.4,37.7z M20,4.3c-0.1,0-0.4,0-0.5,0.3L2.1,34.7 c-0.2,0.3-0.1,0.5,0,0.6c0.1,0.1,0.2,0.3,0.5,0.3h34.7c0.3,0,0.5-0.2,0.5-0.3c0.1-0.1,0.2-0.3,0-0.6L20.5,4.7 C20.4,4.4,20.1,4.3,20,4.3z M20,27c-0.6,0-1-0.4-1-1V11c0-0.6,0.4-1,1-1s1,0.4,1,1v15C21,26.6,20.6,27,20,27z"></path>
            <circle cx="20" cy="31.7" r="1.8"></circle>
          </svg>
          <p class="content--desc-large">Oops, something went wrong.</p>
        </div>
      </div>
      <div class="content--block">
        <h3>What happened?</h3>
        <div class="content--desc">
          Oauth error invalid_request: Missing or invalid client secret
        </div>
      </div>
      <div class="content--block">
        <h3>What can I do?</h3>
        <div class="content--desc">
          <ul>
            <li>Press the back button on your browser.</li>
            <li>Return to your <a href="/admin">admin dashboard</a>.</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="request-id">Request ID: b02057d9-def0-40d4-b896-b65e736df11a-1779073101</div>
  </div>
</body>
</html>
 (CLIENT_ID set: True, CLIENT_SECRET set: True)

In [33]:
######################################################################################
# DANGEROUS FILE, PLEASE RETRACT FROM THIS FILE IF YOU DON'T HAVE ANYTHING TO DO #
######################################################################################

import requests
import set_sy

headers = {
    "X-Shopify-Access-Token": set_sy.get_token(),
    "Content-Type": "application/json",
}
csv_file = "draft_products_deletion_list.xlsx"


i = 0
for product_id in productID_to_delete:
    i+=1

    url = f"https://wooden-ships.myshopify.com/admin/api/2026-01/products/{product_id}.json"
    resp = requests.delete(url=url, headers=headers)
    resp.raise_for_status()
    print(f"{i} product {product_id} is successfully deleted")

1 product 7777741111344 is successfully deleted
2 product 7587930996784 is successfully deleted
3 product 7588158636080 is successfully deleted
4 product 7786664460336 is successfully deleted
5 product 7632549937200 is successfully deleted
6 product 7197535797296 is successfully deleted
7 product 6981853085744 is successfully deleted
8 product 6974115250224 is successfully deleted
9 product 7160261214256 is successfully deleted
10 product 6558802673712 is successfully deleted
11 product 7487014535216 is successfully deleted
12 product 7661709590576 is successfully deleted
13 product 7237858787376 is successfully deleted
14 product 7514151911472 is successfully deleted
15 product 6980134928432 is successfully deleted
16 product 6987895504944 is successfully deleted
17 product 7084192825392 is successfully deleted
18 product 6853810126896 is successfully deleted
19 product 7116347998256 is successfully deleted
20 product 6987956256816 is successfully deleted
21 product 7131232305200 is successfully deleted
22 product 7236901011504 is successfully deleted
23 product 4694717595696 is successfully deleted
24 product 6655269503024 is successfully deleted
25 product 6718413570096 is successfully deleted
26 product 7576718966832 is successfully deleted
27 product 7336828698672 is successfully deleted
28 product 4634734362672 is successfully deleted
29 product 7572550549552 is successfully deleted
30 product 7179618811952 is successfully deleted
31 product 4359699824688 is successfully deleted
32 product 7118575239216 is successfully deleted
33 product 7118574485552 is successfully deleted
34 product 7242281943088 is successfully deleted
35 product 6824214036528 is successfully deleted
36 product 7658998792240 is successfully deleted
37 product 7528474411056 is successfully deleted
38 product 6562963324976 is successfully deleted
39 product 7465251504176 is successfully deleted
40 product 7466402545712 is successfully deleted
41 product 7696272883760 is successfully deleted
42 product 7233342537776 is successfully deleted
43 product 7248324198448 is successfully deleted
44 product 4609958346800 is successfully deleted
45 product 4648953577520 is successfully deleted
46 product 7565102252080 is successfully deleted
47 product 7531864588336 is successfully deleted
48 product 7516033613872 is successfully deleted
49 product 7535348711472 is successfully deleted
50 product 7511721181232 is successfully deleted
51 product 7262888525872 is successfully deleted
52 product 7486758813744 is successfully deleted
53 product 7264107036720 is successfully deleted
54 product 7264118865968 is successfully deleted
55 product 4648956002352 is successfully deleted
56 product 6954321248304 is successfully deleted
57 product 7569205723184 is successfully deleted
58 product 6846926290992 is successfully deleted
59 product 4717707100208 is successfully deleted
60 product 7354962640944 is successfully deleted
61 product 6984287617072 is successfully deleted
62 product 4618414686256 is successfully deleted
63 product 7179622121520 is successfully deleted
64 product 4639855706160 is successfully deleted
65 product 4665386827824 is successfully deleted
66 product 7174866075696 is successfully deleted
67 product 6576126427184 is successfully deleted
68 product 7658550165552 is successfully deleted
69 product 7350465396784 is successfully deleted
70 product 7114290069552 is successfully deleted
71 product 7116557844528 is successfully deleted
72 product 7631813443632 is successfully deleted
73 product 7168660439088 is successfully deleted
74 product 6811979612208 is successfully deleted
75 product 6983086735408 is successfully deleted
76 product 7493153882160 is successfully deleted
77 product 6758628687920 is successfully deleted
78 product 6687328043056 is successfully deleted
79 product 4599546773552 is successfully deleted
80 product 7145037856816 is successfully deleted
81 product 7170851766320 is successfully deleted
82 product 7604023885872 is successfully deleted
83 product 7262869094448 is successfully deleted
84 product 7554956460080 is successfully deleted
85 product 7570783273008 is successfully deleted
86 product 4618409902128 is successfully deleted
87 product 4618440671280 is successfully deleted
88 product 4648967995440 is successfully deleted
89 product 7621209325616 is successfully deleted
90 product 7585496924208 is successfully deleted
91 product 7282216370224 is successfully deleted
92 product 4451986833456 is successfully deleted
93 product 6716671066160 is successfully deleted
94 product 6687460884528 is successfully deleted
95 product 7664589144112 is successfully deleted
96 product 7483272986672 is successfully deleted
97 product 7687196147760 is successfully deleted
98 product 7514158923824 is successfully deleted
99 product 7466435149872 is successfully deleted
100 product 7535355330608 is successfully deleted
101 product 7514176454704 is successfully deleted
102 product 6575497117744 is successfully deleted
103 product 6575551021104 is successfully deleted
104 product 6682158170160 is successfully deleted
105 product 7577945309232 is successfully deleted
106 product 7580298903600 is successfully deleted
107 product 4648970092592 is successfully deleted
108 product 7537925488688 is successfully deleted
109 product 6550578462768 is successfully deleted
110 product 6716807807024 is successfully deleted
111 product 6811881865264 is successfully deleted
112 product 7572755611696 is successfully deleted
113 product 7896637177904 is successfully deleted
114 product 7576737808432 is successfully deleted
115 product 7535759360048 is successfully deleted
116 product 7664629612592 is successfully deleted
117 product 7535348678704 is successfully deleted
118 product 7514196803632 is successfully deleted
119 product 7265767489584 is successfully deleted
120 product 7179626151984 is successfully deleted
121 product 7198386815024 is successfully deleted
122 product 7179626381360 is successfully deleted
123 product 7482143670320 is successfully deleted
124 product 7178558537776 is successfully deleted
125 product 4699625914416 is successfully deleted
126 product 7619551789104 is successfully deleted
127 product 4360106737712 is successfully deleted
128 product 4359700348976 is successfully deleted
129 product 7191871848496 is successfully deleted
130 product 7589562318896 is successfully deleted
131 product 7576721817648 is successfully deleted
132 product 7659090182192 is successfully deleted
133 product 7665250697264 is successfully deleted
134 product 7487162974256 is successfully deleted
135 product 7026652741680 is successfully deleted
136 product 6930170413104 is successfully deleted
137 product 7650128953392 is successfully deleted
138 product 6825308192816 is successfully deleted
139 product 4369810260016 is successfully deleted
140 product 6544427515952 is successfully deleted
141 product 7351833395248 is successfully deleted
142 product 6544451403824 is successfully deleted
143 product 7198762827824 is successfully deleted
144 product 4359700381744 is successfully deleted
145 product 6685653860400 is successfully deleted
146 product 4476367274032 is successfully deleted
147 product 7179550392368 is successfully deleted
148 product 6848814219312 is successfully deleted
149 product 7264899432496 is successfully deleted
150 product 7196981035056 is successfully deleted
151 product 4601095389232 is successfully deleted
152 product 4691533398064 is successfully deleted
153 product 4359700414512 is successfully deleted
154 product 4466337677360 is successfully deleted
155 product 7652716380208 is successfully deleted
156 product 7537290772528 is successfully deleted
157 product 7487181586480 is successfully deleted
158 product 6889080553520 is successfully deleted
159 product 6954322788400 is successfully deleted
160 product 4691970850864 is successfully deleted
161 product 7203043246128 is successfully deleted
162 product 7179564154928 is successfully deleted
163 product 6822418972720 is successfully deleted
164 product 6815045353520 is successfully deleted
165 product 7016058322992 is successfully deleted
166 product 4470489808944 is successfully deleted
167 product 6835660587056 is successfully deleted
168 product 7281150918704 is successfully deleted
169 product 7165890756656 is successfully deleted
170 product 7569958797360 is successfully deleted
171 product 7285391196208 is successfully deleted
172 product 7165379248176 is successfully deleted
173 product 4470769451056 is successfully deleted
174 product 4359700480048 is successfully deleted
175 product 4470770008112 is successfully deleted
176 product 7553007910960 is successfully deleted
177 product 7728348102704 is successfully deleted
178 product 7574888874032 is successfully deleted
179 product 7340886753328 is successfully deleted
180 product 7577102614576 is successfully deleted
181 product 7289333579824 is successfully deleted
182 product 4636227141680 is successfully deleted
183 product 7576703467568 is successfully deleted
184 product 7113955147824 is successfully deleted
185 product 7145883467824 is successfully deleted
186 product 4358763708464 is successfully deleted
187 product 7785031696432 is successfully deleted
188 product 6758638616624 is successfully deleted
189 product 6975309381680 is successfully deleted
190 product 6966901375024 is successfully deleted
191 product 7477783199792 is successfully deleted
192 product 7351020486704 is successfully deleted
193 product 7471733637168 is successfully deleted
194 product 7466493607984 is successfully deleted
195 product 7535354118192 is successfully deleted
196 product 7024999858224 is successfully deleted
197 product 6932366229552 is successfully deleted
198 product 7014370443312 is successfully deleted
199 product 7014931202096 is successfully deleted
200 product 6608619733040 is successfully deleted
201 product 6538883891248 is successfully deleted
202 product 6538888839216 is successfully deleted
203 product 4358764462128 is successfully deleted
204 product 6608622059568 is successfully deleted
205 product 7263677186096 is successfully deleted
206 product 7552962691120 is successfully deleted
207 product 7313867276336 is successfully deleted
208 product 7316779565104 is successfully deleted
209 product 7296166690864 is successfully deleted
210 product 7696569008176 is successfully deleted
211 product 4648415789104 is successfully deleted
212 product 4648416116784 is successfully deleted
213 product 7191859462192 is successfully deleted
214 product 4695317348400 is successfully deleted
215 product 7201108230192 is successfully deleted
216 product 7565563363376 is successfully deleted
217 product 7198389403696 is successfully deleted
218 product 4456377974832 is successfully deleted
219 product 7614320214064 is successfully deleted
220 product 7757539442736 is successfully deleted
221 product 7633484218416 is successfully deleted
222 product 7908756226096 is successfully deleted
223 product 7551311151152 is successfully deleted
224 product 7340422234160 is successfully deleted
225 product 7627270586416 is successfully deleted
226 product 7354581188656 is successfully deleted
227 product 7201175142448 is successfully deleted
228 product 7026378244144 is successfully deleted
229 product 7352235589680 is successfully deleted
230 product 7350459072560 is successfully deleted
231 product 7350704209968 is successfully deleted
232 product 7350704767024 is successfully deleted
233 product 7178570563632 is successfully deleted
234 product 6758639632432 is successfully deleted
235 product 7522995273776 is successfully deleted
236 product 4360093663280 is successfully deleted
237 product 6544474734640 is successfully deleted
238 product 7064928256048 is successfully deleted
239 product 7175148109872 is successfully deleted
240 product 7094464315440 is successfully deleted
241 product 7466444587056 is successfully deleted
242 product 7270491390000 is successfully deleted
243 product 7350459858992 is successfully deleted
244 product 7194855243824 is successfully deleted
245 product 7842997076016 is successfully deleted
246 product 7650182201392 is successfully deleted
247 product 4609850212400 is successfully deleted
248 product 7198766956592 is successfully deleted
249 product 7123291275312 is successfully deleted
250 product 4469631352880 is successfully deleted
251 product 4691986612272 is successfully deleted
252 product 6815035326512 is successfully deleted
253 product 6889304555568 is successfully deleted
254 product 7791588409392 is successfully deleted
255 product 7624695283760 is successfully deleted
256 product 7312552951856 is successfully deleted
257 product 4759586242608 is successfully deleted
258 product 7550045716528 is successfully deleted
259 product 7591919943728 is successfully deleted
260 product 7586992848944 is successfully deleted
261 product 7312729636912 is successfully deleted
262 product 7328956514352 is successfully deleted
263 product 7312729669680 is successfully deleted
264 product 7167689850928 is successfully deleted
265 product 7840866959408 is successfully deleted
266 product 7827912163376 is successfully deleted
267 product 4692172865584 is successfully deleted
268 product 4728116248624 is successfully deleted
269 product 4691539460144 is successfully deleted
270 product 6539495473200 is successfully deleted
271 product 4469081473072 is successfully deleted
272 product 7560295153712 is successfully deleted
273 product 7286981722160 is successfully deleted
274 product 7286978478128 is successfully deleted
275 product 6961042194480 is successfully deleted
276 product 6687391318064 is successfully deleted
277 product 6682183499824 is successfully deleted
278 product 4648970190896 is successfully deleted
279 product 6640074555440 is successfully deleted
280 product 7345733402672 is successfully deleted
281 product 7662256390192 is successfully deleted
282 product 7538589794352 is successfully deleted
283 product 7535366733872 is successfully deleted
284 product 7535357263920 is successfully deleted
285 product 6576040640560 is successfully deleted
286 product 4701597892656 is successfully deleted
287 product 4450292006960 is successfully deleted
288 product 4754438324272 is successfully deleted
289 product 4466169217072 is successfully deleted
290 product 6689527791664 is successfully deleted
291 product 6687463440432 is successfully deleted
292 product 4748845449264 is successfully deleted
293 product 7547291795504 is successfully deleted
294 product 7519969902640 is successfully deleted
295 product 7519969837104 is successfully deleted
296 product 6716710256688 is successfully deleted
297 product 6686940856368 is successfully deleted
298 product 6682158334000 is successfully deleted
299 product 7191874175024 is successfully deleted
300 product 7783896875056 is successfully deleted
301 product 4728598364208 is successfully deleted
302 product 4728594694192 is successfully deleted
303 product 4728596758576 is successfully deleted
304 product 4728593383472 is successfully deleted
305 product 4728591581232 is successfully deleted
306 product 4742049431600 is successfully deleted
307 product 4645811879984 is successfully deleted
308 product 7821470466096 is successfully deleted
309 product 7828168540208 is successfully deleted
310 product 7170959343664 is successfully deleted
311 product 4466172428336 is successfully deleted
312 product 4748810387504 is successfully deleted
313 product 6681447661616 is successfully deleted
314 product 7340895502384 is successfully deleted
315 product 4466199265328 is successfully deleted
316 product 4466204016688 is successfully deleted
317 product 7565163790384 is successfully deleted
318 product 7589889769520 is successfully deleted
319 product 7351667556400 is successfully deleted
320 product 7354584236080 is successfully deleted
321 product 7751811858480 is successfully deleted
322 product 7623529693232 is successfully deleted
323 product 7577696141360 is successfully deleted
324 product 7305555705904 is successfully deleted
325 product 7286994731056 is successfully deleted
326 product 4699611234352 is successfully deleted
327 product 4359700774960 is successfully deleted
328 product 4359700807728 is successfully deleted
329 product 7170978938928 is successfully deleted
330 product 7146996498480 is successfully deleted
331 product 7147002298416 is successfully deleted
332 product 4468364181552 is successfully deleted
333 product 4647918272560 is successfully deleted
334 product 4664483119152 is successfully deleted
335 product 4648983003184 is successfully deleted
336 product 7265934442544 is successfully deleted
337 product 6684479225904 is successfully deleted
338 product 4453882921008 is successfully deleted
339 product 4453865881648 is successfully deleted
340 product 4453860606000 is successfully deleted
341 product 7244777521200 is successfully deleted
342 product 7513691947056 is successfully deleted
343 product 7514348388400 is successfully deleted
344 product 7460676567088 is successfully deleted
345 product 7466513596464 is successfully deleted
346 product 7264087113776 is successfully deleted
347 product 7471704113200 is successfully deleted
348 product 7263950962736 is successfully deleted
349 product 7532997607472 is successfully deleted
350 product 7270828507184 is successfully deleted
351 product 7827924025392 is successfully deleted
352 product 7164256583728 is successfully deleted
353 product 7326071423024 is successfully deleted
354 product 7221371863088 is successfully deleted
355 product 7373775601712 is successfully deleted
356 product 7211334795312 is successfully deleted
357 product 7535356739632 is successfully deleted
358 product 4455554711600 is successfully deleted
359 product 4759645782064 is successfully deleted
360 product 6576133242928 is successfully deleted
361 product 7179626315824 is successfully deleted
362 product 4358233129008 is successfully deleted
363 product 6758641958960 is successfully deleted
364 product 4648968552496 is successfully deleted
365 product 6954516217904 is successfully deleted
366 product 7191404183600 is successfully deleted
367 product 6954327212080 is successfully deleted
368 product 7348543062064 is successfully deleted
369 product 7175819591728 is successfully deleted
370 product 7026780667952 is successfully deleted
371 product 7175817068592 is successfully deleted
372 product 6544534503472 is successfully deleted
373 product 7620878729264 is successfully deleted
374 product 7732360151088 is successfully deleted
375 product 7244775292976 is successfully deleted
376 product 7570490196016 is successfully deleted
377 product 7147043913776 is successfully deleted
378 product 7147016323120 is successfully deleted
379 product 7232257490992 is successfully deleted
380 product 7685604048944 is successfully deleted
381 product 7620830330928 is successfully deleted
382 product 7037460414512 is successfully deleted
383 product 6758644973616 is successfully deleted
384 product 4470716235824 is successfully deleted
385 product 7522388148272 is successfully deleted
386 product 6815474057264 is successfully deleted
387 product 7118535655472 is successfully deleted
388 product 7731120832560 is successfully deleted
389 product 7373863092272 is successfully deleted
390 product 7373854736432 is successfully deleted
391 product 7384402755632 is successfully deleted
392 product 7677541646384 is successfully deleted
393 product 7643237515312 is successfully deleted
394 product 7643214839856 is successfully deleted
395 product 7883455201328 is successfully deleted
396 product 7643216609328 is successfully deleted
397 product 6716717105200 is successfully deleted
398 product 7767873716272 is successfully deleted
399 product 7767509893168 is successfully deleted
400 product 7261186064432 is successfully deleted
401 product 7263777751088 is successfully deleted
402 product 7198395105328 is successfully deleted

In [ ]:
######################################################################################
# DANGEROUS FILE, PLEASE RETRACT FROM THIS FILE IF YOU DON'T HAVE ANYTHING TO DO #
######################################################################################

import requests
import set_sy

headers = {
    "X-Shopify-Access-Token": set_sy.get_token(),
    "Content-Type": "application/json",
}
csv_file = "draft_products_deletion_list.xlsx"


product_ids= []

for product_id in productID_to_delete:
    url = f"https://wooden-ships.myshopify.com/admin/api/2026-01/products/{product_id}.json"
    resp = requests.delete(url=url, headers=headers)
    resp.raise_for_status()
    print(f"product {product_id} is successfully deleted")

product 7534901559344 is successfully deleted
product 7613079552048 is successfully deleted
product 7809622507568 is successfully deleted
product 7587355131952 is successfully deleted
product 7532920635440 is successfully deleted
product 7718860816432 is successfully deleted
product 7588112891952 is successfully deleted
product 4686510817328 is successfully deleted
product 4729063276592 is successfully deleted
product 4686312636464 is successfully deleted
product 7727975465008 is successfully deleted
product 6977216675888 is successfully deleted
product 4641370374192 is successfully deleted
product 7619657957424 is successfully deleted
product 7629182861360 is successfully deleted
product 7623912521776 is successfully deleted
product 7263704186928 is successfully deleted
product 7205042585648 is successfully deleted
product 6547958988848 is successfully deleted
product 7574884548656 is successfully deleted
product 7574890905648 is successfully deleted
product 7574383624240 is successfully deleted
product 7637795078192 is successfully deleted
product 7658083975216 is successfully deleted
product 7650430943280 is successfully deleted
product 4759535747120 is successfully deleted
product 4748810190896 is successfully deleted
product 4759534108720 is successfully deleted
product 4748810158128 is successfully deleted
product 7483620425776 is successfully deleted
product 7524312580144 is successfully deleted
product 7326869356592 is successfully deleted
product 7600723427376 is successfully deleted
product 7530358571056 is successfully deleted
product 7345662427184 is successfully deleted
product 7517067673648 is successfully deleted
product 7486488248368 is successfully deleted
product 7537294573616 is successfully deleted
product 7483594997808 is successfully deleted
product 7430003523632 is successfully deleted
product 3881323823152 is successfully deleted
product 3873489944624 is successfully deleted
product 6686545969200 is successfully deleted
product 6687466356784 is successfully deleted
product 4748807602224 is successfully deleted
product 6985267314736 is successfully deleted
product 7619656843312 is successfully deleted
product 7483757789232 is successfully deleted
product 3873488863280 is successfully deleted
product 7629322649648 is successfully deleted
product 7025121230896 is successfully deleted
product 6985204662320 is successfully deleted
product 7566107050032 is successfully deleted
product 7577743654960 is successfully deleted
product 6558773936176 is successfully deleted
product 6558614192176 is successfully deleted
product 6558770233392 is successfully deleted
product 7631693021232 is successfully deleted
product 7654705856560 is successfully deleted
product 7375547039792 is successfully deleted
product 7459563700272 is successfully deleted
product 7375547072560 is successfully deleted
product 4636162752560 is successfully deleted
product 6687440535600 is successfully deleted
product 7118854750256 is successfully deleted
product 4751888744496 is successfully deleted
product 7696858841136 is successfully deleted
product 7709921640496 is successfully deleted
product 7465649045552 is successfully deleted
product 4748810453040 is successfully deleted
product 4459389616176 is successfully deleted
product 4648424341552 is successfully deleted
product 4358224412720 is successfully deleted
product 4561156374576 is successfully deleted
product 4648425095216 is successfully deleted
product 4596395835440 is successfully deleted
product 6961038032944 is successfully deleted
product 7030136635440 is successfully deleted
product 6688827703344 is successfully deleted
product 7465348300848 is successfully deleted
product 7068266758192 is successfully deleted
product 7019055284272 is successfully deleted
product 4636194537520 is successfully deleted
product 4636194406448 is successfully deleted
product 6687370149936 is successfully deleted
product 4412778086448 is successfully deleted
product 4412778020912 is successfully deleted
product 4413082697776 is successfully deleted
product 4574065033264 is successfully deleted
product 7604879654960 is successfully deleted
product 4358224740400 is successfully deleted
product 6859448483888 is successfully deleted
product 6985169567792 is successfully deleted
product 6849097334832 is successfully deleted
product 7030132047920 is successfully deleted
product 6608560750640 is successfully deleted
product 7207274315824 is successfully deleted
product 7661902561328 is successfully deleted
product 7713401012272 is successfully deleted
product 7661727383600 is successfully deleted
product 7461243191344 is successfully deleted
product 7454792646704 is successfully deleted
product 6897482563632 is successfully deleted
product 4656496312368 is successfully deleted
product 7689366569008 is successfully deleted
product 7661727154224 is successfully deleted
product 7415640064048 is successfully deleted
product 7483431190576 is successfully deleted
product 7432437792816 is successfully deleted
product 7690070818864 is successfully deleted
product 7513719898160 is successfully deleted
product 7459481092144 is successfully deleted
product 7234758803504 is successfully deleted
product 7234751594544 is successfully deleted
product 6544546693168 is successfully deleted
product 6545005543472 is successfully deleted
product 7461250891824 is successfully deleted
product 7514152337456 is successfully deleted
product 7661727449136 is successfully deleted
product 7147569741872 is successfully deleted
product 4466295210032 is successfully deleted
product 6928815685680 is successfully deleted
product 6822397116464 is successfully deleted
product 4452794007600 is successfully deleted
product 7201278820400 is successfully deleted
product 6671418064944 is successfully deleted
product 7115681169456 is successfully deleted
product 6987912511536 is successfully deleted
product 6853809569840 is successfully deleted
product 4742906970160 is successfully deleted
product 6675378962480 is successfully deleted
product 6676980760624 is successfully deleted
product 6805508325424 is successfully deleted
product 6686479482928 is successfully deleted
product 6688260784176 is successfully deleted
product 6686479810608 is successfully deleted
product 6675399344176 is successfully deleted
product 6545339383856 is successfully deleted
product 6853807407152 is successfully deleted
product 4742642827312 is successfully deleted
product 6675377487920 is successfully deleted
product 7283884064816 is successfully deleted
product 7116474253360 is successfully deleted
product 6675386204208 is successfully deleted
product 6676974272560 is successfully deleted
product 6675376996400 is successfully deleted
product 7144885092400 is successfully deleted
product 6795417387056 is successfully deleted
product 6794221912112 is successfully deleted
product 6815821922352 is successfully deleted
product 6671418163248 is successfully deleted
product 6836304478256 is successfully deleted
product 7262841536560 is successfully deleted
product 7296132481072 is successfully deleted
product 7135970295856 is successfully deleted
product 7255585488944 is successfully deleted
product 7019156897840 is successfully deleted
product 6815853117488 is successfully deleted
product 4684595527728 is successfully deleted
product 4736188350512 is successfully deleted
product 6545351180336 is successfully deleted
product 7581940580400 is successfully deleted
product 7577367052336 is successfully deleted
product 6794621452336 is successfully deleted
product 7618265284656 is successfully deleted
product 6982997508144 is successfully deleted
product 6794660347952 is successfully deleted
product 7019001872432 is successfully deleted
product 6816105103408 is successfully deleted
product 7537912545328 is successfully deleted
product 7079724253232 is successfully deleted
product 6815949619248 is successfully deleted
product 4468468940848 is successfully deleted
product 6545336991792 is successfully deleted
product 7197538123824 is successfully deleted
product 7119661203504 is successfully deleted
product 6815292653616 is successfully deleted
product 6655104090160 is successfully deleted
product 7096116576304 is successfully deleted
product 7269461590064 is successfully deleted
product 6676894220336 is successfully deleted
product 7179511038000 is successfully deleted
product 6676879605808 is successfully deleted
product 7149875167280 is successfully deleted
product 7276768755760 is successfully deleted
product 6545348165680 is successfully deleted
product 6545344004144 is successfully deleted
product 6835083608112 is successfully deleted
product 6946738012208 is successfully deleted
product 7263511543856 is successfully deleted
product 6988010225712 is successfully deleted
product 6816050774064 is successfully deleted
product 4637324345392 is successfully deleted
product 7157474394160 is successfully deleted
product 7580165767216 is successfully deleted
product 6852379639856 is successfully deleted
product 6548007747632 is successfully deleted
product 6815795904560 is successfully deleted
product 7203041247280 is successfully deleted
product 7148186140720 is successfully deleted
product 7537914576944 is successfully deleted
product 7544036982832 is successfully deleted
product 7618213707824 is successfully deleted
product 7581569286192 is successfully deleted
product 7537915527216 is successfully deleted
product 7544617926704 is successfully deleted
product 4660866613296 is successfully deleted
product 6795427708976 is successfully deleted
product 4736195690544 is successfully deleted
product 4763990360112 is successfully deleted
product 6676834484272 is successfully deleted
product 6863637217328 is successfully deleted
product 7188690468912 is successfully deleted
product 6815776374832 is successfully deleted
product 7030616129584 is successfully deleted
product 4763993079856 is successfully deleted
product 4473657589808 is successfully deleted
product 7011747037232 is successfully deleted
product 6685035429936 is successfully deleted
product 4358369083440 is successfully deleted
product 1354911613029 is successfully deleted
product 7742555783216 is successfully deleted
product 7643949072432 is successfully deleted
product 4686310703152 is successfully deleted
product 7179612258352 is successfully deleted
product 7168760709168 is successfully deleted
product 6851213328432 is successfully deleted
product 7198390943792 is successfully deleted
product 6863640592432 is successfully deleted
product 7139633201200 is successfully deleted
product 6827773689904 is successfully deleted
product 7138120106032 is successfully deleted
product 7158438821936 is successfully deleted
product 7158968451120 is successfully deleted
product 7558072303664 is successfully deleted
product 7569979244592 is successfully deleted
product 7514092011568 is successfully deleted
product 7572384415792 is successfully deleted
product 7727451865136 is successfully deleted
product 7536676601904 is successfully deleted
product 7629186990128 is successfully deleted
product 7765057765424 is successfully deleted
product 7586934718512 is successfully deleted
product 7525897928752 is successfully deleted
product 7727564128304 is successfully deleted
product 7630494367792 is successfully deleted
product 7541941698608 is successfully deleted
product 7572380844080 is successfully deleted
product 7529988194352 is successfully deleted
product 1360178970725 is successfully deleted
product 7483657715760 is successfully deleted
product 7353468289072 is successfully deleted
product 7560435138608 is successfully deleted
product 7340287787056 is successfully deleted
product 7567473606704 is successfully deleted
product 7403942248496 is successfully deleted
product 7340287885360 is successfully deleted
product 7153438392368 is successfully deleted
product 4634742161456 is successfully deleted
product 6563010281520 is successfully deleted
product 6562942353456 is successfully deleted
product 4451959078960 is successfully deleted
product 4358226608176 is successfully deleted
product 7619170926640 is successfully deleted
product 7713804058672 is successfully deleted
product 7157448966192 is successfully deleted
product 6848889782320 is successfully deleted
product 6835517227056 is successfully deleted
product 7154096668720 is successfully deleted
product 6825423503408 is successfully deleted
product 4759070933040 is successfully deleted
product 6848889487408 is successfully deleted
product 7084585549872 is successfully deleted
product 4653471891504 is successfully deleted
product 7084558385200 is successfully deleted
product 6544482893872 is successfully deleted
product 6815737937968 is successfully deleted
product 7179532206128 is successfully deleted
product 6754575384624 is successfully deleted
product 7085654966320 is successfully deleted
product 7138074492976 is successfully deleted
product 6793654337584 is successfully deleted
product 6684970025008 is successfully deleted
product 7119976726576 is successfully deleted
product 7119975710768 is successfully deleted
product 7119974989872 is successfully deleted
product 7170619932720 is successfully deleted
product 7118586380336 is successfully deleted
product 6684968779824 is successfully deleted
product 7179519197232 is successfully deleted
product 4692013154352 is successfully deleted
product 7085718241328 is successfully deleted
product 7133832642608 is successfully deleted
product 6848889126960 is successfully deleted
product 6815056724016 is successfully deleted
product 4359699791920 is successfully deleted
product 4468399767600 is successfully deleted
product 7350468411440 is successfully deleted
product 7341000753200 is successfully deleted
product 7341016875056 is successfully deleted
product 7269505433648 is successfully deleted
product 7326625005616 is successfully deleted
product 6754900705328 is successfully deleted
product 4677634097200 is successfully deleted
product 7577691226160 is successfully deleted
product 7534058864688 is successfully deleted
product 7579835564080 is successfully deleted
product 7516877684784 is successfully deleted
product 7508216971312 is successfully deleted
product 7179620352048 is successfully deleted
product 7177882992688 is successfully deleted
product 7564803375152 is successfully deleted
product 7865494011952 is successfully deleted
product 7614074781744 is successfully deleted
product 7609208995888 is successfully deleted
product 7774538170416 is successfully deleted
product 7569978916912 is successfully deleted
product 7356554706992 is successfully deleted
product 7283889373232 is successfully deleted
product 7139639754800 is successfully deleted
product 7138120138800 is successfully deleted
product 7197549625392 is successfully deleted
product 7197545005104 is successfully deleted
product 4699552153648 is successfully deleted
product 7269488820272 is successfully deleted
product 7195887960112 is successfully deleted
product 4691538313264 is successfully deleted
product 7564866977840 is successfully deleted
product 7731179323440 is successfully deleted
product 7564846858288 is successfully deleted
product 7306539794480 is successfully deleted
product 7715660234800 is successfully deleted
product 7567705604144 is successfully deleted
product 6685830774832 is successfully deleted
product 6946729295920 is successfully deleted
product 7021349240880 is successfully deleted
product 4648954331184 is successfully deleted
product 6608624386096 is successfully deleted
product 7201094402096 is successfully deleted
product 753449828453 is successfully deleted
product 7263371624496 is successfully deleted
product 4701562765360 is successfully deleted
product 4667405631536 is successfully deleted
product 7455335809072 is successfully deleted
product 7022610022448 is successfully deleted
product 7535367028784 is successfully deleted
product 7263927631920 is successfully deleted
product 7085796818992 is successfully deleted
product 7271319404592 is successfully deleted
product 7096154882096 is successfully deleted
product 7036344205360 is successfully deleted
product 7384883855408 is successfully deleted
product 7019121639472 is successfully deleted
product 6754567356464 is successfully deleted
product 4701567549488 is successfully deleted
product 4742624411696 is successfully deleted
product 7476652408880 is successfully deleted
product 6887900086320 is successfully deleted
product 6754758918192 is successfully deleted
product 7019096375344 is successfully deleted
product 6779599257648 is successfully deleted
product 6754769469488 is successfully deleted
product 4413397303344 is successfully deleted
product 6954303684656 is successfully deleted
product 4358226935856 is successfully deleted
product 6562956967984 is successfully deleted
product 6562950971440 is successfully deleted
product 6716742303792 is successfully deleted
product 4677993594928 is successfully deleted
product 6716752920624 is successfully deleted
product 4677777489968 is successfully deleted
product 4647939964976 is successfully deleted
product 7355063861296 is successfully deleted
product 3873488928816 is successfully deleted
product 7796495974448 is successfully deleted
product 7592213545008 is successfully deleted
product 7353433292848 is successfully deleted
product 7572372783152 is successfully deleted
product 7564801081392 is successfully deleted
product 7390654824496 is successfully deleted
product 7325581672496 is successfully deleted
product 7696281698352 is successfully deleted
product 7682009759792 is successfully deleted
product 7659069702192 is successfully deleted
product 6815699992624 is successfully deleted
product 6974555652144 is successfully deleted
product 6815772442672 is successfully deleted
product 7230428217392 is successfully deleted
product 7550221647920 is successfully deleted
product 7451015872560 is successfully deleted
product 7207169949744 is successfully deleted
product 6975262425136 is successfully deleted
product 6963856900144 is successfully deleted
product 7483760050224 is successfully deleted
product 7214357053488 is successfully deleted
product 7454616813616 is successfully deleted
product 7203180871728 is successfully deleted
product 7226213367856 is successfully deleted
product 4660093714480 is successfully deleted
product 4660093878320 is successfully deleted
product 6993754423344 is successfully deleted
product 7534650785840 is successfully deleted
product 7550365335600 is successfully deleted
product 7466887086128 is successfully deleted
product 7484054798384 is successfully deleted
product 7519961940016 is successfully deleted
product 7658974576688 is successfully deleted
product 7480856543280 is successfully deleted
product 7467479793712 is successfully deleted
product 7467413995568 is successfully deleted
product 7535746089008 is successfully deleted
product 7514018480176 is successfully deleted
product 7484032548912 is successfully deleted
product 7459875782704 is successfully deleted
product 4521762979888 is successfully deleted
product 4648417656880 is successfully deleted
product 6686897635376 is successfully deleted
product 4521752100912 is successfully deleted
product 6608646307888 is successfully deleted
product 4648426045488 is successfully deleted
product 7487036358704 is successfully deleted
product 6562961489968 is successfully deleted
product 6562962898992 is successfully deleted
product 6562962079792 is successfully deleted
product 4521768583216 is successfully deleted
product 4748310872112 is successfully deleted
product 6853023531056 is successfully deleted
product 7227606106160 is successfully deleted
product 7514141458480 is successfully deleted
product 6911601279024 is successfully deleted
product 7443433160752 is successfully deleted
product 7207180992560 is successfully deleted
product 7019683905584 is successfully deleted
product 6911602786352 is successfully deleted

KeyboardInterrupt:

In [ ]:
print(f"{len(productID_to_delete)} Products are successfully deleted")

4256 Products are successfully deleted

In [ ]:
pd.DataFrame(productID_to_delete, columns=["Product ID"]).to_excel("all_deleted_IDs", index=False)

ValueError: No engine for filetype: ''

In [80]:
add_path = "draft_products_deletion_list.xlsx"

In [81]:
df_add = pd.read_excel(add_path)

In [82]:
additional_product_ids_to_delete = df_add["Product ID"].tolist()

In [83]:
######################################################################################
# DANGEROUS FILE, PLEASE RETRACT FROM THIS FILE IF YOU DON'T HAVE ANYTHING TO DO #
######################################################################################

import requests
import set_sy

headers = {
    "X-Shopify-Access-Token": set_sy.get_token(),
    "Content-Type": "application/json",
}
csv_file = "draft_products_deletion_list.xlsx"


i = 0
for product_id in additional_product_ids_to_delete:
    i+=1

    url = f"https://wooden-ships.myshopify.com/admin/api/2026-01/products/{product_id}.json"
    resp = requests.delete(url=url, headers=headers)
    resp.raise_for_status()
    print(f"{i} product {product_id} is successfully deleted")

1 product 7578254278704 is successfully deleted
2 product 7671839129648 is successfully deleted
3 product 7244373524528 is successfully deleted
4 product 7782864617520 is successfully deleted
5 product 7742555553840 is successfully deleted
6 product 7782715064368 is successfully deleted
7 product 7752872951856 is successfully deleted
8 product 7752872525872 is successfully deleted
9 product 7600617553968 is successfully deleted
10 product 7319260692528 is successfully deleted
11 product 7614383587376 is successfully deleted
12 product 7907855466544 is successfully deleted
13 product 7800860704816 is successfully deleted
14 product 7630536507440 is successfully deleted
15 product 7586200649776 is successfully deleted
16 product 7770337148976 is successfully deleted
17 product 7571245072432 is successfully deleted
18 product 7751666466864 is successfully deleted
19 product 7736140038192 is successfully deleted
20 product 7713804156976 is successfully deleted
21 product 4601254445104 is successfully deleted
22 product 6563941777456 is successfully deleted
23 product 6657587347504 is successfully deleted
24 product 4355108405296 is successfully deleted
25 product 4355107618864 is successfully deleted
26 product 4355106930736 is successfully deleted
27 product 6953054011440 is successfully deleted
28 product 7484739682352 is successfully deleted
29 product 7495285604400 is successfully deleted
30 product 6777537069104 is successfully deleted
31 product 3873490075696 is successfully deleted
32 product 2177167392816 is successfully deleted
33 product 4664440258608 is successfully deleted
34 product 7241114026032 is successfully deleted
35 product 7230315724848 is successfully deleted
36 product 6678440083504 is successfully deleted
37 product 6712195186736 is successfully deleted
38 product 7239715881008 is successfully deleted
39 product 7240427536432 is successfully deleted
40 product 6687331156016 is successfully deleted
41 product 7042695987248 is successfully deleted
42 product 7265448820784 is successfully deleted
43 product 7247165882416 is successfully deleted
44 product 6754881830960 is successfully deleted
45 product 7235388112944 is successfully deleted
46 product 7234272034864 is successfully deleted
47 product 7495354548272 is successfully deleted
48 product 7236043014192 is successfully deleted
49 product 6608687136816 is successfully deleted
50 product 7236021878832 is successfully deleted
51 product 6687574556720 is successfully deleted
52 product 6579210879024 is successfully deleted
53 product 7688870690864 is successfully deleted

KeyboardInterrupt: